#!/bin/sh

home=/var/InternerSpeicher/fhem
cd $home

trap "" SIGHUP
modprobe cdc_acm
sleep 2

# Kernel Module for FTDI USB-to-Serial
modprobe ftdi_sio vendor=0x0403 product=0x6001
sleep 2

USBFT=$(grep 0403 /proc/tty/driver/usbserial | cut -d ":" -f1)

echo "FTDI started as device /dev/ttyUSB$USBFT"  

ln -sf $home/FHEM/fhemcmd.sh /var/fhemcmd

PATH=$home:$PATH
export PATH

export LD_LIBRARY_PATH=$home/lib
export PERL5LIB=$home/lib/perl5/site_perl/5.12.2/mips-linux:$home/lib/perl5/site_perl/5.12.2:$home/lib/perl5/5.12.2/mips-linux:$home/lib/perl5/5.12.2

perl fhem.pl fhem.cfg
